### ISSUE TITLE
`car_id` 'int' object has no attribute 'isdigit'

### ISSUE THREAD

**Issue by freinbichler** [JakobLichterfeld/TeslaMate-Telegram-Bot#33]
After upgrading to v0.7.2 I am getting the following error (with and without setting the `CAR_ID` env variable):

```
teslamate-teslamatetelegrambot-1  | Traceback (most recent call last):
teslamate-teslamatetelegrambot-1  |   File "/app/./src/teslamte_telegram_bot.py", line 64, in <module>
teslamate-teslamatetelegrambot-1  |     if not car_id.isdigit() or int(car_id) < 1:
teslamate-teslamatetelegrambot-1  |            ^^^^^^^^^^^^^^
teslamate-teslamatetelegrambot-1  | AttributeError: 'int' object has no attribute 'isdigit'
teslamate-teslamatetelegrambot-1  | Traceback (most recent call last):
teslamate-teslamatetelegrambot-1  |   File "/app/./src/teslamte_telegram_bot.py", line 64, in <module>
teslamate-teslamatetelegrambot-1  |     if not car_id.isdigit() or int(car_id) < 1:
teslamate-teslamatetelegrambot-1  |            ^^^^^^^^^^^^^^
teslamate-teslamatetelegrambot-1  | AttributeError: 'int' object has no attribute 'isdigit'
teslamate-teslamatetelegrambot-1  | Traceback (most recent call last):
teslamate-teslamatetelegrambot-1  |   File "/app/./src/teslamte_telegram_bot.py", line 64, in <module>
teslamate-teslamatetelegrambot-1  |     if not car_id.isdigit() or int(car_id) < 1:
teslamate-teslamatetelegrambot-1  |            ^^^^^^^^^^^^^^
teslamate-teslamatetelegrambot-1  | AttributeError: 'int' object has no attribute 'isdigit'
teslamate-teslamatetelegrambot-1  | Traceback (most recent call last):
teslamate-teslamatetelegrambot-1  |   File "/app/./src/teslamte_telegram_bot.py", line 64, in <module>
teslamate-teslamatetelegrambot-1  |     if not car_id.isdigit() or int(car_id) < 1:
teslamate-teslamatetelegrambot-1  |            ^^^^^^^^^^^^^^
teslamate-teslamatetelegrambot-1  | AttributeError: 'int' object has no attribute 'isdigit'
teslamate-teslamatetelegrambot-1  | Traceback (most recent call last):
teslamate-teslamatetelegrambot-1  |   File "/app/./src/teslamte_telegram_bot.py", line 64, in <module>
teslamate-teslamatetelegrambot-1  |     if not car_id.isdigit() or int(car_id) < 1:
teslamate-teslamatetelegrambot-1  |            ^^^^^^^^^^^^^^
teslamate-teslamatetelegrambot-1  | AttributeError: 'int' object has no attribute 'isdigit'
teslamate-teslamatetelegrambot-1  | Traceback (most recent call last):
teslamate-teslamatetelegrambot-1  |   File "/app/./src/teslamte_telegram_bot.py", line 64, in <module>
teslamate-teslamatetelegrambot-1  |     if not car_id.isdigit() or int(car_id) < 1:
teslamate-teslamatetelegrambot-1  |            ^^^^^^^^^^^^^^
teslamate-teslamatetelegrambot-1  | AttributeError: 'int' object has no attribute 'isdigit'
```

Btw: there is a typo in the filename `teslamte_telegram_bot.py`

**Comment by JakobLichterfeld** [comment]
Thanks for reporting, will try to reproduce and fix accordingly

**Comment by freinbichler** [comment]
The reason should be that `.isdigit()` is a String method, however `car_id` is of type `int`.
However, if I set the environment variable as a string, I get the following error:
`ERROR - Error: Please set the environment variable CAR_ID to a valid number and try again.`

**Comment by JakobLichterfeld** [comment]
Sorry again, was doing too much in parallel and found an issue in my test system. Will fix and release new version by today

**Comment by JakobLichterfeld** [comment]
> Btw: there is a typo in the filename `teslamte_telegram_bot.py`

Good catch!

**Comment by JakobLichterfeld** [comment]
Will release after lunch
